MODE: 'validation'
GPU_IDS: [0, 1, 2, 3]
EVAL_TYPE: 'proposal'
DATASET: 'anet'
USE_ENV: True
USE_AGENT: False
EVAL_SCORE: 'AUC'
TRAIN:
  SPLIT: 'training'
  NUM_EPOCHS: 10
  BATCH_SIZE: 16
  LR: 0.0001
  LOG_DIR: 'runs/r3d_runs/'
  ATTENTION_STEPS: 100
VAL:
  SPLIT: 'validation'
  BATCH_SIZE: 16
TEST:
  SPLIT: 'testing'
  BATCH_SIZE: 16
  #CHECKPOINT_PATH: 'checkpoints/c3d_checkpoints/checkpoint_41/best_AUC.pth'
  #CHECKPOINT_PATH: 'checkpoints/best_checkpoints/best_anet_c3d_env_only/best_AUC.pth'
  CHECKPOINT_PATH: 'checkpoints/best_checkpoints/best_han_anet_c3d/best_AUC.pth'
DATA:
  ANNOTATION_FILE: '../datasets/activitynet/annotations/activity_net.v1-3.min.json'
  #ANNOTATION_FILE: '../datasets/activitynet/annotations/seen+unseen_anet13.json'

  # C3D:
  #ENV_FEATURE_DIR: '../datasets/activitynet/c3d_env_features/'
  AGENT_FEATURE_DIR: '../datasets/activitynet/c3d_agent_features/'

  # R3D Featmap:
  #ENV_FEATURE_DIR: '/mnt/data/r3d_env_feats/'
  ENV_FEATURE_DIR: '/mnt/data/remove_actor/'

  # SlowFast:
  #ENV_FEATURE_DIR: '../datasets/activitynet/slowfast_env_features/'
  #AGENT_FEATURE_DIR: '../datasets/activitynet/slowfast_agent_features/'

  RESULT_PATH: 'results/results.json'
  FIGURE_PATH: 'results/results.pdf'
  TEMPORAL_DIM: 100
  MAX_DURATION: 100
MODEL:
  BOUNDARY_MATCHING_MODULE: 'bmn'
  SCORE_PATH: 'checkpoints/r3d_checkpoints/scores.json'
  CHECKPOINT_DIR: 'checkpoints/r3d_checkpoints/'

  # For TSN features:
  #ENV_DIM: 400
  #AGENT_DIM: 400

  # For C3D features:
  ENV_DIM: 2048
  AGENT_DIM: 2048
  FEAT_DIM: 2048

  # For R3D featmaps:
  #ENV_DIM: 1024
  #AGENT_DIM: 1024
  #ENV_HIDDEN_DIM: 1024
  #AGENT_HIDDEN_DIM: 1024
  #FEAT_DIM: 1024

  TRANSFORMER_DIM: 1024
  TOPK_AGENTS: 4
BMN:
  POST_PROCESS:
    MAX_PROPOSALS: 100
    SOFT_NMS_ALPHA: 0.4
    SOFT_NMS_LOW_THRESHOLD: 0.5
    SOFT_NMS_HIGH_THRESHOLD: 0.9
